Implementing baseline U-Net based on PyTorch.
lunit-io/ocelot23algo pull request #2
Opened 2023-05-19 05:07 UTC by Aavache

# 🚀 Purpose of this PR

Currently, there is only one dummy algorithm to detect cells in the repository. It would be useful for participants to have another reference baseline on how to run algorithms with a popular deep learning framework leveraging the power of GPUs.

The proposed model (U-Net) model was pre-trained with the OCELOT training set. You will find the required reproducibility documentation under `user/unet_example/README.md`. 

Please, be aware that this method is a cell-only baseline, therefore it does not consider the larger tissue patch context.

2023-05-19 07:00 UTC, rjw0205 requested changes
Thanks for your hard effort, I only left one comment!

2023-05-19 07:00 UTC, rjw0205 commented on README.md
> +For more inference examples, please visit `/ocelot23algo/user/unet_example/`.
Can we make this sentence more detailed? 

--> To guide participants with the actual example, we provide a simple baseline algorithm that uses the U-Net architecture. For more details, please visit [ocelot23algo/user/unet_example/](https://github.com/lunit-io/ocelot23algo/tree/feature/unet-example/user/unet_example).

2023-05-22 02:10 UTC, Aavache commented on README.md
> +For more inference examples, please visit `/ocelot23algo/user/unet_example/`.
Thank you for the comment @rjw0205! I applied the change.

2023-05-22 02:17 UTC, rjw0205 approved these changes
Thanks for your effort, LGTM!

2023-05-22 02:19 UTC, merged